cache:
  directories:
  - node_modules # cache node_module
language: node_js # set language to node_js
node_js:
  10.16.3 # use node version 7
branches:
  only: 
  - master # auto build and deploy in only master branch
script: # run after installed
- npm install # install node module
- npm run build # build project
install:
  npm install -g firebase-tools # install firebase-cli
api_key:
    secure: ${Trairat_job}
after_success:
- firebase use --token ${FIREBASE_TOKEN} # set firebase token
- firebase use --add ${PROJECT_ID} # set current project
- firebase deploy --non-interactive --token "${FIREBASE_TOKEN}" # deploy project
